[tasks.build]
command = "wasm-pack"
args = [
  "build",
  "--target", "web",
  "--out-dir", "./public/wasm",
  "--out-name", "script",
]

[tasks.build-release]
command = "wasm-pack"
args = [
  "build",
  "--target", "web",
  "--out-dir", "./public/wasm",
  "--out-name", "script",
  "--release",
]

# https://www.npmjs.com/package/http-server
[tasks.serve]
command = "http-server"
cwd = "public"
args = [
  "--gzip",
]
